language: julia
os:
  - linux
julia:
  - 1.2.0
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; 
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.add("Documenter");
                                    Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
      after_sucess: skip
