language: julia

os:
  - linux
julia:
  - 1.3.0
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3

after_success:
  - julia --project=coverage/ -e 'using Pkg;
                                  Pkg.instantiate();
                                  using Coverage;
                                  Codecov.submit(Codecov.process_folder());'

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; 
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
